[package]
name = "trashctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.6"
clap_complete = "3.2.2"
anyhow = "1.0"